name: "Titanium Android build"
description: "Installs Titanium SDK and builds your Android apk store or debug app"

inputs:
  version:
    description: "The Titanium SDK version you want to install. e.g. 12.0.0.GA"
    required: false
    default: "12.0.0.GA"
  keystore:
    description: 'Base64 encoded keystore file. Required for a store build'
    required: false
    default: ''
  keystore_secret:
    description: 'Keystore password. Required for a store build'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install Titanium SDK
      uses:  m1ga/titanium-install@v1
      with:
        version: ${{ inputs.version }}

    - name: Build app (store)
      env:
          ANDROID_KEYSTORE: ${{ inputs.keystore }}
          ANDROID_KEYSTORE_SECRET: ${{ inputs.keystore_secret }}
      shell: bash
      if: ${{ env.ANDROID_KEYSTORE_SECRET != '' }}
      run: |
        echo $ANDROID_KEYSTORE | base64 --decode > keystore.keystore
        ti build -p android -T dist-playstore -K keystore.keystore -O ./dist -P $ANDROID_KEYSTORE_SECRET
    - name: Build app (debug)
      env:
          ANDROID_KEYSTORE: ${{ inputs.keystore }}
          ANDROID_KEYSTORE_SECRET: ${{ inputs.keystore_secret }}
      shell: bash
      if: ${{ env.ANDROID_KEYSTORE_SECRET == '' }}
      run: |
        ti build -p android -b -l info

    - name: Upload APK (store)
      uses: actions/upload-artifact@v3
      with:
        name: my APK
        path: ./dist/*.apk

    - name: Upload APK (debug)
      uses: actions/upload-artifact@v3
      with:
        name: my APK
        path: ./build/android/app/build/outputs/apk/debug/app-debug.apk

branding:
  icon: "smartphone"
  color: "red"
