name: Test Workflow
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        ti_version: ["12.0.0.GA"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Titanium SDK
        uses: ./
        with:
          version: ${{ matrix.ti_version }}
